exclude:
- releases/*
- Wurst Client/*
- Wurst updater/*

gems:
  - jekyll-sitemap
  - jemoji

timezone: Europe/Berlin

title: Wurst Client

paginate: 5

paginate_path: "/news/:num"

permalink: /news/:year-:month-:day-:title/index.html
